<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\creational\DesignPatterns.Creational.csproj" />
    <ProjectReference Include="..\structural\DesignPatterns.Structural.csproj" />
    <ProjectReference Include="..\behavioral\DesignPatterns.Behavioral.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
